print('dati valoare lui n:')
n=int(input('n='))
produsul=1*n
produsul2=2*n
produsul3=3*n
produsul4=4*n
produsul5=5*n
produsul6=6*n
produsul7=7*n
produsul8=8*n
produsul9=9*n
produsul10=10*n
print('1*n=',produsul)
print('2*n=',produsul2)
print('3*n=',produsul3)
print('4*n=',produsul4)
print('5*n=',produsul5)
print('6*n=',produsul6)
print('7*n=',produsul7)
print('8*n=',produsul8)
print('9*n=',produsul9)
print('10*n=',produsul10)